version: '3.8'
services:
  db:
    image: 'postgres:12'
    ports:
      - '5432:5432'
    volumes:
      - ./temp/pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth-example-dev-db
